# frozen_string_literal: true

require 'spec_helper'
require 'tmpdir'
require 'fileutils'
require 'belt/cli/generate_command'

RSpec.describe 'Generate command — _id field detection' do
  describe '.parse_field' do
    it 'treats conversation_id as a reference to conversation' do
      result = Belt::CLI::GenerateCommand.parse_field('conversation_id:integer')
      expect(result).to eq({ name: 'conversation', type: 'references', referenced_model: 'conversation' })
    end

    it 'treats user_id as a reference to user' do
      result = Belt::CLI::GenerateCommand.parse_field('user_id:string')
      expect(result).to eq({ name: 'user', type: 'references', referenced_model: 'user' })
    end

    it 'treats post_id (no type) as a reference to post' do
      result = Belt::CLI::GenerateCommand.parse_field('post_id')
      expect(result).to eq({ name: 'post', type: 'references', referenced_model: 'post' })
    end

    it 'does not treat id alone as a reference' do
      result = Belt::CLI::GenerateCommand.parse_field('id:string')
      expect(result).to eq({ name: 'id', type: 'string' })
    end

    it 'does not treat fields containing _id mid-word as references' do
      result = Belt::CLI::GenerateCommand.parse_field('valid:string')
      expect(result).to eq({ name: 'valid', type: 'string' })
    end

    it 'still handles explicit references type' do
      result = Belt::CLI::GenerateCommand.parse_field('post:references')
      expect(result).to eq({ name: 'post', type: 'references', referenced_model: 'post' })
    end
  end

  describe 'model generation with _id field' do
    let(:tmpdir) { Dir.mktmpdir }

    before do
      @original_dir = Dir.pwd
      Dir.chdir(tmpdir)

      FileUtils.mkdir_p('config')
      FileUtils.mkdir_p('lambda/models')
      FileUtils.mkdir_p('lambda/controllers/chat')
      FileUtils.mkdir_p('lambda/lib/routes')
      FileUtils.mkdir_p('infrastructure/modules/app')

      File.write('config/routes.rb', <<~RUBY)
        Belt.application.routes.draw do
          gateway :chat do
            resources :conversations, tables: [:conversations]
          end
        end
      RUBY

      File.write('config/contracts.rb', <<~RUBY)
        Belt.application.schema.define do
        end
      RUBY

      File.write('lambda/models/conversation.rb', <<~RUBY)
        # frozen_string_literal: true

        class Conversation < ApplicationRecord
          attr_accessor :title, :last_message_at, :last_message
        end
      RUBY

      allow(Belt::CLI::TablesCommand).to receive(:sync_all_environments)
    end

    after do
      Dir.chdir(@original_dir)
      FileUtils.rm_rf(tmpdir)
    end

    it 'generates belongs_to from a conversation_id field' do
      Belt::CLI::GenerateCommand.new(
        'model', 'message',
        Belt::CLI::GenerateCommand.parse_field('conversation_id:integer').then { |f| [f] } +
          [{ name: 'body', type: 'text' }]
      ).generate

      content = File.read('lambda/models/message.rb')
      expect(content).to include('belongs_to :conversation')
    end

    it 'does not add conversation_id as an attr_accessor' do
      Belt::CLI::GenerateCommand.new(
        'model', 'message',
        [Belt::CLI::GenerateCommand.parse_field('conversation_id:integer'),
         { name: 'body', type: 'text' }]
      ).generate

      content = File.read('lambda/models/message.rb')
      expect(content).not_to include(':conversation_id')
    end

    it 'injects has_many into the parent model when it exists' do
      Belt::CLI::GenerateCommand.new(
        'model', 'message',
        [Belt::CLI::GenerateCommand.parse_field('conversation_id:integer'),
         { name: 'body', type: 'text' }]
      ).generate

      content = File.read('lambda/models/conversation.rb')
      expect(content).to include('has_many :messages')
    end
  end

  describe 'table generation includes GSI from _id field' do
    let(:tmpdir) { Dir.mktmpdir }

    before do
      @original_dir = Dir.pwd
      Dir.chdir(tmpdir)

      FileUtils.mkdir_p('config')
      FileUtils.mkdir_p('lambda/models')
      FileUtils.mkdir_p('infrastructure/modules/app')

      File.write('config/contracts.rb', <<~RUBY)
        Belt.application.schema.define do
        end
      RUBY
    end

    after do
      Dir.chdir(@original_dir)
      FileUtils.rm_rf(tmpdir)
    end

    it 'generates ConversationIndex GSI in dynamodb.tf' do
      # Write a model with belongs_to :conversation (as generated by _id detection)
      File.write('lambda/models/message.rb', <<~RUBY)
        # frozen_string_literal: true

        class Message < ApplicationRecord
          belongs_to :conversation

          attr_accessor :body
        end
      RUBY

      Belt::CLI::TablesCommand.new(quiet: true).run

      tf_content = File.read('infrastructure/modules/app/dynamodb.tf')
      expect(tf_content).to include('ConversationIndex')
      expect(tf_content).to include('conversationId')
    end
  end
end
