# frozen_string_literal: true

require_relative 'app_detection'
require_relative 'env_resolver'
require_relative 'terraform_command'
require_relative '../inflector'

module Belt
  module CLI
    class TablesCommand
      SCHEMA_FILE = 'infrastructure/schema.tf.rb'
      MODULE_DIR = 'infrastructure/modules/app'

      include AppDetection

      def self.run(args)
        env = EnvResolver.resolve(args)

        if env.nil?
          puts 'Usage: belt setup tables [environment]'
          puts "\nReads schema.tf.rb and generates dynamodb.tf in the app module."
          puts 'You can also set BELT_ENV to skip the environment argument.'
          puts "\nExamples:"
          puts '  belt setup tables'
          puts '  belt setup tables dev'
          puts '  BELT_ENV=dev belt setup tables'
          exit 1
        end

        new(env).run
      end

      # Automatically sync dynamodb.tf in the app module.
      # Called by generators after updating schema.tf.rb.
      def self.sync_all_environments
        return unless File.exist?(SCHEMA_FILE)

        # With the module approach, we only need to generate once into modules/app/
        new(nil, quiet: true).run
      end

      def initialize(env, quiet: false)
        @env = env
        @quiet = quiet
        @app_name = detect_app_name
      end

      def run
        validate!
        models = parse_schema
        if models.empty?
          puts "No models found in #{SCHEMA_FILE}" unless @quiet
          return
        end

        generate_dynamodb_tf(models)
      end

      private

      def validate!
        unless File.exist?(SCHEMA_FILE)
          abort "Error: #{SCHEMA_FILE} not found. Run `belt generate resource` first." unless @quiet
          return
        end
        return if Dir.exist?(MODULE_DIR)

        return if @quiet

        abort "Error: Module directory not found at #{MODULE_DIR}/.\n" \
              'Run `belt new` to create a project with the correct structure.'
      end

      def parse_schema
        return [] unless File.exist?(SCHEMA_FILE)

        parser = SchemaParser.new
        schema_content = File.read(SCHEMA_FILE)

        # Replace DSL wrapper with direct parser call
        inner = schema_content.sub(/\A(?:Belt\.application)\.schema\.draw do\n?/, '').sub(/\n?end\s*\z/, '')
        inner.strip!

        return [] if inner.empty? || inner.match?(/\A\s*\z/m)

        parser.instance_eval(inner, SCHEMA_FILE)
        parser.models
      end

      def generate_dynamodb_tf(models)
        dest = File.join(MODULE_DIR, 'dynamodb.tf')
        existing_content = File.exist?(dest) ? File.read(dest) : nil
        new_content = render_dynamodb(models)

        # Skip if content is unchanged
        return if existing_content == new_content

        File.write(dest, new_content)

        if @quiet
          verb = existing_content ? 'update' : 'create'
          puts "  #{verb}  #{dest}"
        else
          puts "  create  #{dest}"
          puts "\n✓ Generated DynamoDB tables for #{models.size} model(s):"
          models.each { |m| puts "    • #{Belt::Inflector.pluralize(m[:name])}" }
          puts "\nRun `belt deploy` to create them."
        end
      end

      def render_dynamodb(models)
        blocks = models.map { |m| render_table(m) }
        "# Auto-generated by Belt from schema.tf.rb\n" \
          "# Do not edit manually — re-run `belt setup tables`\n\n#{blocks.join("\n\n")}\n"
      end

      def render_table(model)
        name = table_name(model[:name])
        <<~HCL
          resource "aws_dynamodb_table" "#{Belt::Inflector.pluralize(model[:name])}" {
            name         = "#{name}"
            billing_mode = "PAY_PER_REQUEST"
            hash_key     = "id"

            attribute {
              name = "id"
              type = "S"
            }

            tags = {
              Name        = "#{name}"
              Environment = var.environment
              ManagedBy   = "Terraform"
            }
          }
        HCL
      end

      def table_name(model_name)
        "#{@app_name}-${var.environment}-#{Belt::Inflector.pluralize(model_name)}"
      end

      # Minimal DSL parser for schema.tf.rb
      class SchemaParser
        attr_reader :models

        def initialize
          @models = []
        end

        def model(name, &block)
          model_def = ModelParser.new
          model_def.instance_eval(&block) if block
          @models << { name: name.to_s, fields: model_def.fields }
        end
      end

      class ModelParser
        attr_reader :fields

        def initialize
          @fields = []
        end

        def field(name, **opts)
          @fields << { name: name.to_s, type: opts[:type]&.to_s || 'string' }
        end
      end
    end
  end
end
