# frozen_string_literal: true

require_relative 'env_resolver'
require_relative 'terraform_command'
require_relative '../inflector'

module Belt
  module CLI
    class TablesCommand
      SCHEMA_FILE_CANDIDATES = ['config/schema.tf.rb', 'infrastructure/schema.tf.rb'].freeze
      MODULE_DIR = 'infrastructure/modules/app'

      def self.run(args)
        # Environment argument accepted for backwards compatibility but unused —
        # dynamodb.tf lives in infrastructure/modules/app and uses var.environment.
        EnvResolver.resolve(args)

        new.run
      end

      # Automatically sync dynamodb.tf in the app module.
      # Called by generators after updating schema.tf.rb.
      def self.sync_all_environments
        return unless schema_file_path

        new(quiet: true).run
      end

      def self.schema_file_path
        SCHEMA_FILE_CANDIDATES.find { |f| File.exist?(f) }
      end

      def initialize(quiet: false)
        @quiet = quiet
      end

      def run
        validate!
        models = parse_schema
        if models.empty?
          puts "No models found in #{SCHEMA_FILE}" unless @quiet
          return
        end

        generate_dynamodb_tf(models)
      end

      private

      def validate!
        schema_file = self.class.schema_file_path
        unless schema_file
          unless @quiet
            abort 'Error: No schema.tf.rb found (checked config/ and infrastructure/). ' \
                  'Run `belt generate resource` first.'
          end
          return
        end
        return if Dir.exist?(MODULE_DIR)

        return if @quiet

        abort "Error: Module directory not found at #{MODULE_DIR}/.\n" \
              'Run `belt new` to create a project with the correct structure.'
      end

      def parse_schema
        schema_file = self.class.schema_file_path
        return [] unless schema_file && File.exist?(schema_file)

        parser = SchemaParser.new
        schema_content = File.read(schema_file)

        # Replace DSL wrapper with direct parser call
        inner = schema_content.sub(/\A(?:Belt\.application)\.schema\.draw do\n?/, '').sub(/\n?end\s*\z/, '')
        inner.strip!

        return [] if inner.empty? || inner.match?(/\A\s*\z/m)

        parser.instance_eval(inner, schema_file)
        parser.models
      end

      def generate_dynamodb_tf(models)
        dest = File.join(MODULE_DIR, 'dynamodb.tf')
        existing_content = File.exist?(dest) ? File.read(dest) : nil
        new_content = render_dynamodb(models)

        # Skip if content is unchanged
        return if existing_content == new_content

        File.write(dest, new_content)

        if @quiet
          verb = existing_content ? 'update' : 'create'
          puts "  #{verb}  #{dest}"
        else
          puts "  create  #{dest}"
          puts "\n✓ Generated DynamoDB tables for #{models.size} model(s):"
          models.each { |m| puts "    • #{Belt::Inflector.pluralize(m[:name])}" }
          puts "\nRun `belt deploy` to create them."
        end
      end

      def render_dynamodb(models)
        blocks = models.map { |m| render_table(m) }
        "# Auto-generated by Belt from schema.tf.rb\n" \
          "# Do not edit manually — re-run `belt setup tables`\n\n#{blocks.join("\n\n")}\n"
      end

      def render_table(model)
        name = table_name(model[:name])
        custom_indexes = model[:indexes] || []

        # Collect all custom index attribute names, deduplicating against built-in ones
        builtin_attrs = Set.new(%w[id _recent_pk createdAt])
        extra_attrs = []
        custom_indexes.each do |idx|
          extra_attrs << idx[:partition_key] unless builtin_attrs.include?(idx[:partition_key])
          builtin_attrs.add(idx[:partition_key])
          if idx[:sort_key] && !builtin_attrs.include?(idx[:sort_key])
            extra_attrs << idx[:sort_key]
            builtin_attrs.add(idx[:sort_key])
          end
        end

        lines = []
        lines << "resource \"aws_dynamodb_table\" \"#{Belt::Inflector.pluralize(model[:name])}\" {"
        lines << "  name         = \"#{name}\""
        lines << '  billing_mode = "PAY_PER_REQUEST"'
        lines << '  hash_key     = "id"'
        lines << ''
        lines << '  attribute {'
        lines << '    name = "id"'
        lines << '    type = "S"'
        lines << '  }'
        lines << ''
        lines << '  attribute {'
        lines << '    name = "_recent_pk"'
        lines << '    type = "S"'
        lines << '  }'
        lines << ''
        lines << '  attribute {'
        lines << '    name = "createdAt"'
        lines << '    type = "S"'
        lines << '  }'

        extra_attrs.each do |attr|
          lines << ''
          lines << '  attribute {'
          lines << "    name = \"#{attr}\""
          lines << '    type = "S"'
          lines << '  }'
        end

        lines << ''
        lines << '  global_secondary_index {'
        lines << '    name            = "RecentIndex"'
        lines << '    hash_key        = "_recent_pk"'
        lines << '    range_key       = "createdAt"'
        lines << '    projection_type = "ALL"'
        lines << '  }'

        custom_indexes.each do |idx|
          lines << ''
          lines << '  global_secondary_index {'
          lines << "    name            = \"#{idx[:name]}\""
          lines << "    hash_key        = \"#{idx[:partition_key]}\""
          lines << "    range_key       = \"#{idx[:sort_key]}\"" if idx[:sort_key]
          lines << '    projection_type = "ALL"'
          lines << '  }'
        end

        lines << ''
        lines << '  point_in_time_recovery {'
        lines << '    enabled = var.enable_pitr'
        lines << '  }'
        lines << ''
        lines << '  deletion_protection_enabled = var.deletion_protection'
        lines << ''
        lines << '  tags = {'
        lines << "    Name        = \"#{name}\""
        lines << '    Environment = var.environment'
        lines << '    ManagedBy   = "Terraform"'
        lines << '  }'
        lines << '}'

        lines.join("\n")
      end

      def table_name(model_name)
        "${var.app_name}-${var.environment}-#{Belt::Inflector.pluralize(model_name)}"
      end

      # Minimal DSL parser for schema.tf.rb
      class SchemaParser
        attr_reader :models

        def initialize
          @models = []
        end

        def model(name, &block)
          model_def = ModelParser.new
          model_def.instance_eval(&block) if block
          @models << { name: name.to_s, fields: model_def.fields, indexes: model_def.indexes }
        end
      end

      class ModelParser
        attr_reader :fields, :indexes

        def initialize
          @fields = []
          @indexes = []
        end

        def field(name, **opts)
          @fields << { name: name.to_s, type: opts[:type]&.to_s || 'string' }
        end

        def index(name, partition_key:, sort_key: nil)
          @indexes << { name: name.to_s, partition_key: partition_key.to_s, sort_key: sort_key&.to_s }
        end
      end
    end
  end
end
